//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practical_for_BD.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chart
    {
        public long ID { get; set; }
        public long ID_employers { get; set; }
        public System.TimeSpan start_working_day { get; set; }
        public System.TimeSpan end_working_day { get; set; }
        public long ID_transport { get; set; }
        public System.TimeSpan break_time { get; set; }
        public int number_of_watch { get; set; }
    
        public virtual Employers Employers { get; set; }
        public virtual Transports Transports { get; set; }
    }
}
