//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practical_for_BD.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Day_routs
    {
        public long ID { get; set; }
        public long ID_weekday { get; set; }
        public long ID_transport { get; set; }
        public long ID_route { get; set; }
    
        public virtual Routes Routes { get; set; }
        public virtual Transports Transports { get; set; }
        public virtual Weekdays Weekdays { get; set; }
    }
}
