//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practical_for_BD.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employers
    {
        public Employers()
        {
            this.Chart = new HashSet<Chart>();
        }
    
        public long ID { get; set; }
        public long ID_post { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public long ID_gender { get; set; }
        public string Pathronymic { get; set; }
        public string Phone_number { get; set; }
        public System.DateTime Birthday { get; set; }
        public long ID_Salary { get; set; }
        public decimal bonus { get; set; }
    
        public virtual ICollection<Chart> Chart { get; set; }
        public virtual Genders Genders { get; set; }
        public virtual Posts Posts { get; set; }
        public virtual Salary Salary { get; set; }
    }
}
