//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practical_for_BD.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Genders
    {
        public Genders()
        {
            this.Employers = new HashSet<Employers>();
            this.Users = new HashSet<Users>();
        }
    
        public long ID { get; set; }
        public string Gender { get; set; }
    
        public virtual ICollection<Employers> Employers { get; set; }
        public virtual ICollection<Users> Users { get; set; }
    }
}
