//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practical_for_BD.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Public_transportEntities1 : DbContext
    {
        private static Public_transportEntities1 _context;
        public Public_transportEntities1()
            : base("name=Public_transportEntities1")
        {
        }

        public static Public_transportEntities1 GetContext()
        {
                if (_context == null)
                    _context = new Public_transportEntities1();
                return _context;
            
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Chart> Chart { get; set; }
        public DbSet<Day_routs> Day_routs { get; set; }
        public DbSet<Districts> Districts { get; set; }
        public DbSet<Employers> Employers { get; set; }
        public DbSet<Genders> Genders { get; set; }
        public DbSet<Group> Group { get; set; }
        public DbSet<Missed_route> Missed_route { get; set; }
        public DbSet<Pavilions> Pavilions { get; set; }
        public DbSet<Permissions> Permissions { get; set; }
        public DbSet<Posts> Posts { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<Roles_and_permissions> Roles_and_permissions { get; set; }
        public DbSet<Routes> Routes { get; set; }
        public DbSet<Salary> Salary { get; set; }
        public DbSet<Schedul> Schedul { get; set; }
        public DbSet<Schedule_changes> Schedule_changes { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Transport_stop> Transport_stop { get; set; }
        public DbSet<Transporter> Transporter { get; set; }
        public DbSet<Transports> Transports { get; set; }
        public DbSet<Types_transport> Types_transport { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<Weekdays> Weekdays { get; set; }
    }
}
