//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practical_for_BD.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permissions
    {
        public Permissions()
        {
            this.Roles_and_permissions = new HashSet<Roles_and_permissions>();
        }
    
        public long ID { get; set; }
        public string Permission { get; set; }
    
        public virtual ICollection<Roles_and_permissions> Roles_and_permissions { get; set; }
    }
}
