//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practical_for_BD.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Routes
    {
        public Routes()
        {
            this.Day_routs = new HashSet<Day_routs>();
            this.Schedul = new HashSet<Schedul>();
            this.Transports = new HashSet<Transports>();
            this.Users = new HashSet<Users>();
        }
    
        public long ID { get; set; }
        public string Number_route { get; set; }
        public long ID_district_start { get; set; }
        public long ID_districts_finish { get; set; }
        public System.TimeSpan Follow_up_time { get; set; }
        public long ID_transporter { get; set; }
        public System.TimeSpan Time_start { get; set; }
        public System.TimeSpan Time_finish { get; set; }
        public long ID_employers { get; set; }
    
        public virtual ICollection<Day_routs> Day_routs { get; set; }
        public virtual Districts Districts { get; set; }
        public virtual Districts Districts1 { get; set; }
        public virtual Transporter Transporter { get; set; }
        public virtual ICollection<Schedul> Schedul { get; set; }
        public virtual ICollection<Transports> Transports { get; set; }
        public virtual ICollection<Users> Users { get; set; }
    }
}
