//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practical_for_BD.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public Salary()
        {
            this.Employers = new HashSet<Employers>();
        }
    
        public long ID { get; set; }
        public decimal salary1 { get; set; }
    
        public virtual ICollection<Employers> Employers { get; set; }
    }
}
