//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practical_for_BD.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedul
    {
        public long ID { get; set; }
        public Nullable<long> route_id { get; set; }
        public Nullable<long> transport_stop_id { get; set; }
        public System.TimeSpan start_time { get; set; }
        public System.TimeSpan end_time { get; set; }
    
        public virtual Routes Routes { get; set; }
        public virtual Transport_stop Transport_stop { get; set; }
    }
}
