//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practical_for_BD.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transport_stop
    {
        public Transport_stop()
        {
            this.Schedul = new HashSet<Schedul>();
        }
    
        public long ID { get; set; }
        public string Name_stop { get; set; }
        public long ID_district { get; set; }
        public Nullable<long> ID_pavilion { get; set; }
    
        public virtual Districts Districts { get; set; }
        public virtual Pavilions Pavilions { get; set; }
        public virtual ICollection<Schedul> Schedul { get; set; }
    }
}
