//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practical_for_BD.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Types_transport
    {
        public Types_transport()
        {
            this.Transports = new HashSet<Transports>();
        }
    
        public long ID { get; set; }
        public string Name_transport { get; set; }
    
        public virtual ICollection<Transports> Transports { get; set; }
    }
}
